import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#444749',
        'tertiary-container': '#727577',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#ffffff',
        'surface-dim': '#dadada',
        'on-tertiary': '#e0e3e5',
        'secondary-fixed-dim': '#ababab',
        'primary': '#000000',
        'surface-container': '#eeeeee',
        'tertiary': '#383c3e',
        'primary-fixed-dim': '#3323cc',
        'inverse-surface': '#2f3131',
        'on-primary-container': '#ffffff',
        'background': '#f9f9f9',
        'inverse-on-surface': '#f0f1f1',
        'surface': '#f9f9f9',
        'outline': '#777777',
        'secondary': '#5e5e5e',
        'surface-variant': '#e2e2e2',
        'surface-bright': '#f9f9f9',
        'error-container': '#ffdad6',
        'secondary-container': '#d4d4d4',
        'on-surface': '#1a1c1c',
        'primary-fixed': '#4d44e3',
        'on-secondary-container': '#1b1b1b',
        'primary-container': '#2606c2',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#ffffff',
        'surface-container-highest': '#e2e2e2',
        'on-secondary-fixed': '#1b1b1b',
        'on-secondary-fixed-variant': '#3b3b3b',
        'error': '#ba1a1a',
        'secondary-fixed': '#c6c6c6',
        'inverse-primary': '#c3c0ff',
        'on-primary-fixed-variant': '#e2dfff',
        'surface-container-low': '#f3f3f4',
        'on-surface-variant': '#474747',
        'surface-container-high': '#e8e8e8',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#5c5f61',
        'on-tertiary-fixed-variant': '#e0e3e5',
        'on-primary-fixed': '#ffffff',
        'surface-tint': '#4d44e3',
        'on-error-container': '#410002',
        'on-primary': '#e2dfff',
        'outline-variant': '#c6c6c6',
        'on-background': '#1a1c1c',
      },
      fontFamily: {
        headline: ['var(--font-space-grotesk)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
        space: ['var(--font-space-grotesk)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
        handwritten: ['var(--font-caveat)', 'cursive'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
